spring:
  rabbitmq:
    exchanges:
      client-registration: amq.fanout
    queue:
      client-registration: client-registration
    host: localhost
    port: 15672
    username: guest
    password: guest
server:
  port: 9090
spring:
  application:
  data:
    rest:
      base-path: /api/v1/
  jackson:
    mapper:
      default-view-inclusion: true

jpa:
  show-sql: true
  database: POSTGRESQL
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  generate-ddl: false
  hibernate:
    ddl-auto: validate
  properties:

  datasource:
    jpa:
      show-sql: true
      database: POSTGRESQL
      generate-ddl: false
      properties:
        hibernate:
          format_sql: true
          naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          jdbc:
            lob:
              non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        web: DEBUG

#eureka:
#  instance:
 #   hostname: es.neifi.clientservice.client-service
  #es.neifi.clientservice.client:
   # registerWithEureka: true
    #fetchRegistry: true
  #serviceUrl:
   # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


